### ISSUE TITLE
Les icones du header istex n'apparaissent pas sous firefox/ubuntu sur certains des sites istex

### ISSUE THREAD

**Issue by tporquet** [istex/web-header#1]
Sous Firefox 53.0.3 (64 bits) / Ubuntu, les icônes du header ne s'affichent pas sur :
- le site "principal" istex.fr
- http://demo.istex.fr/
- http://widgets.istex.fr/
![capture du 2017-06-01 12-55-04](https://cloud.githubusercontent.com/assets/2981650/26681194/965b31da-46dc-11e7-8824-aa9886a9cfdf.png)

Alors que pas de problème constaté pour
https://api.istex.fr/documentation/
https://addons.istex.fr/
http://blog.istex.fr/
où les icones apparaissent bien.

Aucun souci non plus avec Chromium 'Version 58.0.3029.110 Built on Ubuntu , running on Ubuntu 16.04 (64-bit))

**Comment by niederlec** [comment]
C'est sûrement lié au fait que les icônes ont été modifiées (ce ne sont plus des vraies images, mais des caractères de la police "[Awesome fonts](http://fontawesome.io/icons/)". 
Essaie de recharger la page en vidant le cache (Control + F5 sous Firefox)

**Comment by tporquet** [comment]
sans succès...

Et pour la barre qui s'affiche sur http://blog.istex.fr/, il ne manque qu'un caractère (pour "status") alors que les autres s'affichent :
![capture du 2017-06-01 16-46-46](https://cloud.githubusercontent.com/assets/2981650/26685341/18b94326-46ea-11e7-8488-77a00b13c8c3.png)

**Comment by niederlec** [comment]
Bizarre, je me souviens avoir eu le même comportement il y a quelques temps, mais je m'en étais débarassé à coup de CTRL-F5. Je suis presque sûr que c'est un phénomène de cache quand-même.
Si tu as l'occasion, tu pourrais tester depuis un autre poste ou navigateur ?

**Comment by tporquet** [comment]
Tu as raison : pas de souci depuis un autre poste sous ubuntu + firefox (même version)
Je ferme !
